# Hito 1

-   Giu, Felipe, Jaime y Karla

```{r}
athlete_events <- read.csv("athlete_events.csv", encoding = "UTF-8", as.is = F)
gdp_per_capita <- read.csv("gdp_per_capita.csv", encoding = "UTF-8", as.is = F)
```

```{r}
athlete_events1 <- athlete_events
library(dplyr)

athlete_events1 <- athlete_events1 %>%
  mutate(Sex_bin = case_when(
    Sex == "F" ~ 0,
    Sex == "M" ~ 1
  )
  )

athlete_events1 <- athlete_events1 %>%
  mutate(Medal_num = case_when(
    is.na(Medal) ~ 0,
    Medal == "Bronze" ~ 1,
    Medal == "Silver" ~ 2,
    Medal == "Gold" ~ 3
  )
  )

athlete_events1 <- athlete_events1 %>%
  mutate(Medal_bin = case_when(
    is.na(Medal) ~ 0,
    Medal == "Bronze" ~ 1,
    Medal == "Silver" ~ 1,
    Medal == "Gold" ~ 1
  )
  )
```

```{r}
summary(athlete_events1)
```

```{r}
library(dplyr)
athlete_events2 <- athlete_events[c("Sex", "Medal")]

athlete_events2 <- athlete_events2 %>%
  mutate(Medal_bin = case_when(
    is.na(Medal) ~ 0,
    Medal %in% c("Bronze", "Silver", "Gold") ~ 1
  )
  )%>%
  filter(Medal_bin==1)%>%
  select(-Medal)

barplot(table(athlete_events2$Sex))
```

```{r}
gdp_per_capita1 <- gdp_per_capita
gdp_per_capita1$mean <- rowMeans(gdp_per_capita1[,-c(1,2)], na.rm=TRUE)
#gdp_per_capita1
```

# Matriz de correlación

```{r}
#Fix Null a estandarizado con Height 175 y Weight a 70
library(tidyverse)
atletas_std  <- athlete_events1 %>%
  mutate(
    Height = as.numeric(Height),
    Height = case_when(
      is.na(Height)~ 175,
      is.na(Height)==FALSE ~ Height
      
      


  )
  )

atletas_std  <- atletas_std %>%
  mutate(Weight = case_when(
    is.na(Weight)==TRUE  ~ 70,
    is.na(Weight)==FALSE ~ Weight
  )
  )

data_correlacion <- atletas_std %>%
  select(Sex_bin, Height,  Weight,Year ,Medal_bin)
MCorrelacion<- cor(data_correlacion)


```

```{r}
MCorrelacion
```

# Histograma de participación según el género

```{r}

barplot(table(athlete_events1$Sex)  , main = "Histograma de participación según el género", xlab= "Género",ylab = "Cantidad de participantes", ylim=c(0,250000))
```
